# Generated by Django 5.1.4 on 2025-02-06 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('image', models.ImageField(null=True, upload_to='customer_images/')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.CharField(max_length=20)),
                ('card_id', models.CharField(max_length=25)),
                ('price', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('image', models.ImageField(null=True, upload_to='car_images/')),
                ('license_image', models.ImageField(null=True, upload_to='license_images/')),
                ('licnse_id', models.CharField(max_length=20)),
                ('national_number', models.CharField(max_length=30)),
                ('car_type', models.CharField(max_length=30)),
                ('car_id', models.CharField(max_length=20)),
                ('born_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('driveing', 'driveing'), ('available', 'available')], max_length=30)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pocket', models.FloatField(default=0.0)),
                ('endpocketdate', models.DateTimeField()),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude_of_drop', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude_of_drop', models.DecimalField(decimal_places=6, max_digits=9)),
                ('status', models.CharField(choices=[('E', 'E'), ('C', 'C'), ('D', 'D'), ('A', 'A'), ('B', 'B')], max_length=50)),
                ('decription', models.TextField()),
                ('weight', models.FloatField(null=True)),
                ('distance', models.DecimalField(decimal_places=6, max_digits=9)),
                ('shorter_distance', models.DecimalField(decimal_places=6, max_digits=9)),
                ('price', models.IntegerField(null=True)),
                ('time', models.TimeField(null=True)),
                ('ride_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customers')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.drivers')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customers')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.drivers')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='DriversReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('review', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customers')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.drivers')),
                ('Transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='CutomersReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('review', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customers')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.drivers')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.transaction')),
            ],
        ),
    ]
