# Generated by Django 5.1.4 on 2025-02-07 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='decription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='ride_date',
            new_name='ride_added_date',
        ),
        migrations.AddField(
            model_name='customers',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('onride', 'onride')], default='available', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='car_type',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('driveing', 'driveing')], max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customers'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('A', 'A'), ('D', 'D'), ('B', 'B'), ('C', 'C'), ('E', 'E')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
