# Generated by Django 5.1.4 on 2025-02-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_licnse_id_drivers_license_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='status',
            field=models.CharField(choices=[('onride', 'onride'), ('available', 'available')], max_length=30),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='endpocketdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='speed',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='status',
            field=models.CharField(choices=[('driveing', 'driveing'), ('available', 'available')], max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='distance',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='shorter_distance',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('D', 'D'), ('C', 'C'), ('E', 'E'), ('A', 'A'), ('F', 'F'), ('B', 'B')], max_length=50),
        ),
    ]
