# Generated by Django 5.1.4 on 2025-02-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_customers_status_alter_drivers_endpocketdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('onride', 'onride')], max_length=30),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('driveing', 'driveing')], max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('A', 'A'), ('E', 'E'), ('C', 'C'), ('B', 'B'), ('F', 'F'), ('D', 'D')], max_length=50),
        ),
    ]
