# Generated by Django 5.1.4 on 2025-02-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_customers_status_alter_drivers_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='status',
            field=models.CharField(choices=[('onride', 'onride'), ('available', 'available')], max_length=30),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='status',
            field=models.CharField(choices=[('driveing', 'driveing'), ('available', 'available')], max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('A', 'A'), ('F', 'F'), ('C', 'C'), ('D', 'D'), ('B', 'B'), ('E', 'E')], max_length=50),
        ),
    ]
