# Generated by Django 5.1.4 on 2025-02-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_customers_status_alter_drivers_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivers',
            name='pocket',
        ),
        migrations.AddField(
            model_name='drivers',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('onride', 'onride')], max_length=30),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('driveing', 'driveing')], max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('F', 'F'), ('B', 'B'), ('D', 'D'), ('A', 'A'), ('E', 'E'), ('C', 'C')], max_length=50),
        ),
    ]
