# Generated by Django 5.1.4 on 2025-02-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_price_drivers_pocket_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='status',
            field=models.CharField(choices=[('onride', 'onride'), ('available', 'available')], max_length=30),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='status',
            field=models.CharField(choices=[('driveing', 'driveing'), ('available', 'available')], max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('F', 'F'), ('A', 'A'), ('D', 'D'), ('C', 'C'), ('B', 'B'), ('E', 'E')], max_length=50),
        ),
    ]
